#ifndef SETTINGS_H_ // include guard
#define SETTINGS_H_

#define BACKGROUND_COLOR 0

#define SEP "&"
#define DATE_SEP "%"
#define FILE_OUT_CLIENTS "data/clients.txt"
#define FILE_OUT_MOVIES "data/movies.txt"
#define CLIENT_TEXT_COLOR 3
#define CLIENT_BACKGROUND_COLOR BACKGROUND_COLOR
#define MOVIES_TEXT_COLOR 1
#define MOVIES_BACKGROUND_COLOR BACKGROUND_COLOR
#define INTERFACE_TEXT_COLOR 12
#define INTERFACE_BACKGROUND_COLOR BACKGROUND_COLOR
#define CHOICE_TEXT_COLOR 4
#define CLIENT_BACKGROUND_COLOR BACKGROUND_COLOR
#define FIRST_ROW_TEXT_COLOR 6
#define FIRST_ROW_BACKGROUND_COLOR BACKGROUND_COLOR

#endif